area/core:
  - changed-files:
      - any-glob-to-any-file:
          - "src/ErrorOr/*.cs"

area/aspnetcore:
  - changed-files:
      - any-glob-to-any-file:
          - "src/ErrorOr/AspNetCore/**"

area/features:
  - changed-files:
      - any-glob-to-any-file:
          - "src/ErrorOr/Features/**"

area/serialization:
  - changed-files:
      - any-glob-to-any-file:
          - "src/ErrorOr/Serialization/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
