name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE (#$NUMBER)"
categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "CI & Build"
    labels:
      - "ci"
      - "build"
  - title: "Chores"
    labels:
      - "chore"
      - "maintenance"
template: |
  ## Changes
  $CHANGES
