name: Bug Report
description: Report a problem or regression in ErrorOr
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
      placeholder: Describe the issue clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET version
      options:
        - .NET 10
        - .NET 8
        - .NET 6
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: erroror-version
    attributes:
      label: ErrorOr version
      placeholder: e.g. 3.1.0
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: Paste a minimal reproducible example.
      render: shell
